### ISSUE TITLE
[MM] Autorest.cli generates incorrect api.yml for sub resource Account of NetApp

### ISSUE THREAD

**Issue by neil-yechenwei** [Azure/autorest.cli#16] opened 2019-09-18 03:40 UTC
I am trying to generate api.yml for sub resource "Account" of NetApp. After generated api.yml with command "docker run --rm -i -t -v C:/terraform/projects/azure-rest-api-specs:/azure-rest-api-specs -v C:/terraform/generated:/generated zikalino/autorest.cli /azure-rest-api-specs/specification/netapp/resource-manager/readme.md", I found the api.yml missed many necessary fields like "properties.activeDirectories" and etc. This is the API doc https://docs.microsoft.com/zh-cn/rest/api/netapp/accounts/createorupdate of new resource "NetAppAccounts". Attached the input file "readme.md" and output file "api.yml".

[api.zip](https://github.com/Azure/autorest.cli/files/3624335/api.zip)
[readme.zip](https://github.com/Azure/autorest.cli/files/3624336/readme.zip)

**Comment by chunyu3** [comment] 2019-10-15 08:45
PR : https://github.com/Azure/autorest.cli/pull/35

**Comment by chunyu3** [comment] 2019-10-17 02:31
The issue is fixed in PR https://github.com/Azure/autorest.cli/pull/35

**Comment by neil-yechenwei** [comment] 2019-10-18 01:51
After tested against the fix, the intermediate files for netapp account can be generated successfully and the properties I randomly picked up also can be added to this intermediate file correctly. Thanks for the fix.

**Closed as completed** 2019-10-18 01:51 UTC
Labels: P0
