### ISSUE TITLE
`batchapplication` api.yaml fix

### ISSUE THREAD

**Issue by JunyiYi** [Azure/autorest.cli#13] opened 2019-06-25 23:12 UTC
Only the `prefix`, `Properties` and `list` are blocking issues, others are not.

* [x] Remove [`prefix`](https://github.com/Azure/magic-module-specs/blob/master/batchapplication/api.yaml#L3)
* [ ] Rename [`list`](https://github.com/Azure/magic-module-specs/blob/master/batchapplication/api.yaml#L181) to `list_by_parent`
* [ ] Remove `input: true` from a pure output attribute (for example [`id`](https://github.com/Azure/magic-module-specs/blob/master/batchapplication/api.yaml#L242))
* [ ] In Go SDK, [`Properties`](https://github.com/Azure/magic-module-specs/blob/master/batchapplication/api.yaml#L48) in `Create`, `Update` and `Read` are named as [`ApplicationProperties`](https://github.com/Azure/azure-sdk-for-go/blob/master/services/batch/mgmt/2018-12-01/batch/models.go#L869).

**Comment by chunyu3** [comment] 2019-10-18 03:32
the issue is fixed.
close it.

**Closed as completed by chunyu3** 2019-10-18 03:32 UTC
