### ISSUE TITLE
Properly support arrays in the UX (!ruby/object:Api::Type::Array)

### ISSUE THREAD

**Issue by zikalino** [Azure/autorest.cli#11] opened 2019-06-17 22:43 UTC
After studying recent version of the spec here:

autorest.devops shall use
    !ruby/object:Api::Type::Array: an array of any type.
with
    !ruby/object:Api::Type::NestedObject: a structure containing sub-properties.

for arrays.

Previously I assumed that MM somehow magically maps the UX structure to **SDKTypeDefinition::ComplexArrayObject** without specifically defining arrays

**Comment by chunyu3** [comment] 2019-10-11 07:15
Duplicate of #26

**Comment by chunyu3** [comment] 2019-10-12 06:28
the duplicate #26 issue is fixed.
close this issue.

**Closed as completed by chunyu3** 2019-10-12 06:28 UTC
